## The Tensorflow Trials

For much of the past week, you've been using tensors with your Deep Learning models. Over the course of today's challenges, you'll be manipulating tensors extensively and working with some unconventional model architectures.


In this warm up, you'll be introduced to some new methods.

All the methods here are going to make tackling challenges later in the day 100x easier, so if you do get stuck later on, make sure you come back here to see how you achieved the right answers.

In [ ]:
import tensorflow as tf

A) Use `tf.ones` to create a tensor `a` filled with ones of shape (3,3).

In [ ]:
a=tf.ones([3,3])
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

B) Use tf.expand_dims to make `a` an object of shape (1,3,3) called `b`.

In [ ]:
b=tf.expand_dims(a,axis=0)
b

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

C) Create a tensor `c` filled with zeroes of size (9,1)

In [ ]:
c=tf.zeros(9,1)
c

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

D) Reshape `c` to be of shape (1, 3, 3). Name it `d`.

In [ ]:
d=tf.reshape(c,[1,3,3])
d

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

E) Use `tf.matmul` to matrix multiply `b` and `d` with each other and now assign the tensor to `e`.

In [ ]:
e=tf.matmul(b,d)
e

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

F) Below is a `numpy` array. Convert it to a tensor named `array_tensor`. Then use `tf.cast` to ensure it is of dtype `float` not `int`. Assign the result to `f`.

In [ ]:
import numpy as np

In [ ]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [ ]:
f=tf.cast(array,dtype='float')
f

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

G) Select the values in the __last column__ of `f` and save this to `g`. To be clear, `g` should have shape (4,) and contain the values `3,3,6,9`.

In [ ]:
g=f[0,:,2]
g

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 6., 9.], dtype=float32)>

H) Expand the dimensions of g so that it's of shape (4,1). Assign this to `h`.

In [ ]:
h=tf.expand_dims(g,axis=0)
h

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[3., 3., 6., 9.]], dtype=float32)>

H) Multiply e with f, using `tf.matmul` with the optional `transpose_b` argument (`e` must come first in your positional arguments, then `f`). Assign this to `h`.

In [ ]:
h=tf.matmul(e,f,transpose_b=True)
h

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

I) Create a `(10,10)` tensor filled with ones. Then use `tf.linalg.band_part()` to mask out the upper triangle of the matrix (i.e. the upper triangle should all be 0s). Assign to `i`.

In [ ]:
i=tf.linalg.band_part(tf.ones((10,10)),num_lower=-1, num_upper=0)
i

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

J) Take the `number_list` below and make it a tensor. Assign it to `j`.

In [ ]:
number_list = [1,2,3,4,8]

In [ ]:
import torch
j=torch.tensor(number_list)
j

tensor([1, 2, 3, 4, 8])

K) Use `tf.expand_dims` to make `j` into a tensor of shape (1,5). Assign to `k`.

In [ ]:
k=tf.expand_dims(j,axis=0)
list(k)
k

<tf.Tensor: shape=(1, 5), dtype=int64, numpy=array([[1, 2, 3, 4, 8]])>

L) Use `tf.tile` to repeat `k` 50 times, with an eventual shape of `(50,5)`. Assign to `l`.

In [ ]:
l=tf.tile(k,multiples=[50,1])
l

<tf.Tensor: shape=(50, 5), dtype=int64, numpy=
array([[1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 

M) Use a simple Boolean statement to create a tensor containing `True` values for where `l` is 3  and `False` for where it is not 3. Assign to `m`

In [ ]:
m = (l == 3)
print (m)

tf.Tensor(
[[False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]

N) Divide every value in you variable `l` (read as "L") by 3. Assign to `n`.

In [ ]:
n=tf.divide(l,3)
n

<tf.Tensor: shape=(50, 5), dtype=float64, numpy=
array([[0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333

O) Use `tf.concat()` to take the list of two tensors below of shape (5,5) and (5,5) each and turn them into a final tensor of shape (10,5). Assign to `o`. Think carefully about the concation axis.

In [ ]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]

In [ ]:
o=tf.concat(tensor_list,axis=0)
o

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

### Check your answers

In [ ]:
from nbresult import ChallengeResult

result = ChallengeResult('tensors',
                            a = a,
                            b = b,
                            c = c,
                            d_shape = d.shape,
                            e = e,
                            f = f,
                            g = g,
                            h = h,
                            i = i,
                            j = j,
                            k = k,
                            l = l,
                            m = m,
                            n = n,
                            o_shape = o.shape
)

result.write()
print(result.check())

ModuleNotFoundError: No module named 'nbresult'

### Great work 🔥

Now it's time to get stuck into some modelling!